POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVmM2E1NmVhMjkyZmMwNWY0MjI4ZjQzMSIsImlhdCI6MTU5NzY2MjcyNX0.Y5Uh3V8r5b1L__IbQ5xCs7t4ZOUynrsE6PFkx9jY0Mc

{
  "content": "new note",
  "important": true
}